### ISSUE TITLE
Arrays in Python

### ISSUE THREAD

**Issue by SamyakJain2020** [SamyakJain2020/Data-Structure-Arrays#4]
- Introduction to Arrays
-  Complexity Analysis of Arrays
-  Implementation of Arrays
-  Advantages and Disadvantages of Arrays

**Comment by ridz0326** [comment]
I would like to work on implementing Arrays in Python.

**Comment by SamyakJain2020** [comment]
Ok Cool.
ALL THE BEST !!!
